# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180605_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='license_author',
        ),
        migrations.AddField(
            model_name='exercise',
            name='licence_author',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, to='exercises.Author'),
        ),
    ]
