# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-05 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20180605_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='licence_author',
            new_name='license_author',
        ),
    ]
