# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20180605_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, to='exercises.Author'),
        ),
    ]
