# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-07 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180606_0854'),
        ('exercises', '0009_auto_20180607_1246'),
    ]

    operations = [
    ]
