# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='extra_meal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
