# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180606_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
