# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180607_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyuserprofile',
            name='key',
            field=models.TextField(blank=True),
        ),
    ]
