# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge'),
        ('core', '0014_auto_20180608_0335'),
    ]

    operations = [
    ]
